In [1]:
import numpy as np
a= np.array([1,2,3])
b=np.array([4,5,6])
c=[]
for i in range(len(a)):
    x=a[i]+b[i]
    c.append(x)
result = np.array(c)
c

[5, 7, 9]

In [2]:
a = np.array([1,2,3])
scalar = 6
for i in range(len(a)):
    a[i]=a[i]*scalar
a

array([ 6, 12, 18])

In [4]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
a = np.arange(1,7)
b = a.reshape((2,1,3))
b

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [15]:
ex = np.array([0,1,0,0,0,1,1,1])
result = np.array(ex,dtype='bool')
result

array([False,  True, False, False, False,  True,  True,  True])

In [17]:
ex = np.array([2,4,5,3,7,8,5,4])
result = np.array(ex,dtype='float')
result

array([2., 4., 5., 3., 7., 8., 5., 4.])

In [22]:
a= np.array([[1,2,3],[4,5,6]])
b= np.array([[6,7,8,9],[0,8,65,3]])
result = np.hstack((a,b))
result

array([[ 1,  2,  3,  6,  7,  8,  9],
       [ 4,  5,  6,  0,  8, 65,  3]])

In [29]:
ex = np.linspace(0,100,5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [32]:
a = np.ones((2,3),dtype = 'int')
b = a*5
b

array([[5, 5, 5],
       [5, 5, 5]])

In [42]:
a= np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5],[7,8],[5,6]])
print(np.matmul(a,b)) #matmul = matrix multiplication of 2 matrix

[[33 39]
 [81 96]]
