In [1]:
import numpy as np

In [2]:
#1
list1 = [1,2,3,4,4]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 4])

In [5]:
#2
arr2 = np.random.randint(7,16,16)
arr2.reshape(4,4)

array([[13, 12, 14, 12],
       [ 8, 15, 14, 14],
       [12, 11, 15, 15],
       [13, 11,  8, 14]])

In [7]:
#3
arr3 = np.zeros(10)
arr3[5]=11
arr3

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [8]:
#4
arr4 = np.array([1,2,3,4,5,6,7])
result = arr4[::-1]
result

array([7, 6, 5, 4, 3, 2, 1])

In [41]:
#5 dim=5,5
arr5 = np.ones((5,5))
arr5[1:-1,1:-1]=0
arr5

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#6

In [12]:
#7
arr7 = np.arange(1,10)
arr7= np.append(arr7,[200])
arr7

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 200])

In [16]:
#8
arr8 = np.random.randint(1,100,5) # celcius
farenhite = arr8*1.8 +32
farenhite

array([136.4, 165.2, 190.4,  96.8, 131. ])

In [18]:
#9
arr9 = np.array([[1,2,3],[4,5,6]])
size = arr9.size

6

In [50]:
#10
same = []
arr10 = np.array([2,4,5,6,7,8,9,9])
arr10_2 = np.array([6,4,3,3,5,6])

for ele in arr10:
    if ele in arr10_2:
        same.append(ele)
same

[4, 5, 6]

In [23]:
#11
arr11_ones = np.ones((2,2))
arr11_zeros = np.zeros((2,2))

In [27]:
#12
arr12 = np.random.randint(1,100,16)
result = arr12.reshape(4,4)
result

array([[40, 32,  7,  3],
       [64, 59, 17,  1],
       [17, 59, 85, 88],
       [ 8, 76, 30, 35]])

In [30]:
#13
example = np.array([2,3,5,3,6,6,7])
arr13 = np.array(example , dtype = float )
arr13

array([2., 3., 5., 3., 6., 6., 7.])

In [31]:
#14
arr14 = np.ones((3,5))
result = arr14*2
result.reshape(3,5)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [34]:
#15
arr15_1 = np.eye(4)
arr15_2 = np.eye(4)
arr15 = np.array([arr15_1,arr15_2])
arr15.shape

(2, 4, 4)

In [56]:
#16
arr16 = np.linspace(2,5,20)
arr16_result = np.log(arr16)
arr16_result

array([0.69314718, 0.76913309, 0.83975065, 0.90570862, 0.96758403,
       1.02585293, 1.08091271, 1.13309846, 1.18269541, 1.22994829,
       1.27506873, 1.3182409 , 1.35962611, 1.39936644, 1.43758766,
       1.47440163, 1.50990832, 1.54419739, 1.5773496 , 1.60943791])

In [47]:
#17
non_zero = 0
arr17 = np.array([1,3,7,0,0,0,0,4,2,4,0,0,0])
result = arr17[(arr17 != 0)]
result.size
# for ele in arr17:
#     if ele!=0:
#         non_zero+=1
# non_zero

6

In [45]:
#18
sum_num = 0
arr18 = np.arange(1,100)
# for ele in arr18:
#     if ele%3==0 or ele%5==0:
#         sum_num+=ele
# sum_num
result = arr18[(arr18%3==0) | (arr18%5==0)]
result.sum()


2318